In [6]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import log_loss
from sklearn.metrics import roc_curve
from sklearn.metrics import auc
from sklearn import svm

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import itertools
import pickle

import time

<h2>3000</h2>

In [20]:
X = pd.read_csv('conc_3000.csv', index_col=[0]).sample(frac=1).reset_index(drop=True)
X.head()

android.intent.action.ACTION_PICK_ACTIVITY  \
0                                           0   
1                                           0   
2                                           0   
3                                           0   
4                                           0   

   android.intent.action.ACTION_PACKAGE_FULLY_REMOVED  \
0                                                  0    
1                                                  0    
2                                                  0    
3                                                  0    
4                                                  0    

   android.intent.action.ACTION_SHOW_APP_INFO  \
0                                           0   
1                                           0   
2                                           0   
3                                           0   
4                                           0   

   android.permission.READ_SYNC_STATS  android.permission.INTERNET  \
0                                   0                            1   
1                                   0                            1   
2                                   0                            1   
3                                   0                            1   
4                                   0                            1   

   android.software.app_widgets  android.permission.MANAGE_SOUND_TRIGGER  \
0                             0                                        0   
1                             0                                        0   
2                             0                                        0   
3                             0                                        0   
4                             0                                        0   

   android.permission.MANAGE_FINGERPRINT  \
0                                      0   
1                                      0   
2                                      0   
3                                      0   
4                                      0   

   android.permission.START_TASKS_FROM_RECENTS  \
0                                            0   
1                                            0   
2                                            0   
3                                            0   
4                                            0   

   android.permission.COPY_PROTECTED_DATA  \
0                                       0   
1                                       0   
2                                       0   
3                                       0   
4                                       0   

                               ...                               \
0                              ...                                
1                              ...                                
2                              ...                                
3                              ...                                
4                              ...                                

   android.intent.action.ACTION_LOCKED_BOOT_COMPLETED  \
0                                                  0    
1                                                  0    
2                                                  0    
3                                                  0    
4                                                  0    

   android.permission.SET_INPUT_CALIBRATION  android.software.home_screen  \
0                                         0                             0   
1                                         0                             0   
2                                         0                             0   
3                                         0                             0   
4                                         0                             0   

   android.permission.RECEIVE_WIFI_CREDENTIAL_CHANGE  \
0                                                  0   
1                                 

In [21]:
Y = X.pop('LABEL').values
Y

array([1, 1, 1, ..., 0, 0, 1])

In [22]:
X_train, X_test, Y_train, Y_test = train_test_split(X.values, Y, test_size=0.2)

In [8]:
clf = svm.SVC(kernel='rbf', gamma=0.1, C=100)
start = time.time()
clf.fit(X_train, Y_train)
end = time.time()
print(end - start)

1.4743266105651855


In [31]:
Y_result = clf.predict(X_test)

print('Accuracy: %.2f' % accuracy_score(Y_test, Y_result))
PRF = precision_recall_fscore_support(Y_test, Y_result, average='macro')
print('Precision: %.2f' % PRF[0])
print('Recall: %.2f' % PRF[1])
print('F1: %.2f' % PRF[2])
print('Logarithmic loss: %.2f' % log_loss(Y_test, Y_result,normalize=True))

Accuracy: 0.90
Precision: 0.90
Recall: 0.90
F1: 0.90
Logarithmic loss: 3.43


In [32]:
# save the model to disk
filename = 'svm_3000.sav'
pickle.dump(clf, open(filename, 'wb'))

In [33]:
print(Y_test)
print(Y_result)

[0 1 1 ... 0 0 1]
[0 1 1 ... 0 0 1]


<h2>100</h2>

In [10]:
X = pd.read_csv('conc_100.csv', index_col=[0]).sample(frac=1).reset_index(drop=True)
Y = X.pop('LABEL').values
X_train, X_test, Y_train, Y_test = train_test_split(X.values, Y, test_size=0.2)

In [11]:
clf = svm.SVC(kernel='rbf', gamma=0.1, C=100)
start = time.time()
clf.fit(X_train, Y_train)
end = time.time()
print(end - start)
Y_result = clf.predict(X_test)

print('Accuracy: %.2f' % accuracy_score(Y_test, Y_result))
PRF = precision_recall_fscore_support(Y_test, Y_result, average='macro')
print('Precision: %.2f' % PRF[0])
print('Recall: %.2f' % PRF[1])
print('F1: %.2f' % PRF[2])
print('Logarithmic loss: %.2f' % log_loss(Y_test, Y_result,normalize=True))

0.027370691299438477
Accuracy: 0.82
Precision: 0.82
Recall: 0.83
F1: 0.82
Logarithmic loss: 6.04


In [37]:
# save the model to disk
filename = 'svm_100.sav'
pickle.dump(clf, open(filename, 'wb'))

<h2>500</h2>

In [14]:
X = pd.read_csv('conc_500.csv', index_col=[0]).sample(frac=1).reset_index(drop=True)
Y = X.pop('LABEL').values
X_train, X_test, Y_train, Y_test = train_test_split(X.values, Y, test_size=0.2)

In [15]:
clf = svm.SVC(kernel='rbf', gamma=0.1, C=100)
start = time.time()
clf.fit(X_train, Y_train)
end = time.time()
print(end - start)
Y_result = clf.predict(X_test)

print('Accuracy: %.2f' % accuracy_score(Y_test, Y_result))
PRF = precision_recall_fscore_support(Y_test, Y_result, average='macro')
print('Precision: %.2f' % PRF[0])
print('Recall: %.2f' % PRF[1])
print('F1: %.2f' % PRF[2])
print('Logarithmic loss: %.2f' % log_loss(Y_test, Y_result,normalize=True))

0.2590813636779785
Accuracy: 0.86
Precision: 0.87
Recall: 0.86
F1: 0.86
Logarithmic loss: 4.84


In [40]:
# save the model to disk
filename = 'svm_500.sav'
pickle.dump(clf, open(filename, 'wb'))

<h2>1000</h2>

In [16]:
X = pd.read_csv('conc_1000.csv', index_col=[0]).sample(frac=1).reset_index(drop=True)
Y = X.pop('LABEL').values
X_train, X_test, Y_train, Y_test = train_test_split(X.values, Y, test_size=0.2)

In [17]:
clf = svm.SVC(kernel='rbf', gamma=0.1, C=100)
start = time.time()
clf.fit(X_train, Y_train)
end = time.time()
print(end - start)
Y_result = clf.predict(X_test)

print('Accuracy: %.2f' % accuracy_score(Y_test, Y_result))
PRF = precision_recall_fscore_support(Y_test, Y_result, average='macro')
print('Precision: %.2f' % PRF[0])
print('Recall: %.2f' % PRF[1])
print('F1: %.2f' % PRF[2])
print('Logarithmic loss: %.2f' % log_loss(Y_test, Y_result,normalize=True))

0.862297773361206
Accuracy: 0.88
Precision: 0.88
Recall: 0.88
F1: 0.87
Logarithmic loss: 4.32


In [50]:
# save the model to disk
filename = 'svm_1000.sav'
pickle.dump(clf, open(filename, 'wb'))

<h2>2000</h2>

In [20]:
X = pd.read_csv('conc_2000.csv', index_col=[0]).sample(frac=1).reset_index(drop=True)
Y = X.pop('LABEL').values
X_train, X_test, Y_train, Y_test = train_test_split(X.values, Y, test_size=0.2)

In [21]:
clf = svm.SVC(kernel='rbf', gamma=0.1, C=100)
start = time.time()
clf.fit(X_train, Y_train)
end = time.time()
print(end - start)
Y_result = clf.predict(X_test)

print('Accuracy: %.2f' % accuracy_score(Y_test, Y_result))
PRF = precision_recall_fscore_support(Y_test, Y_result, average='macro')
print('Precision: %.2f' % PRF[0])
print('Recall: %.2f' % PRF[1])
print('F1: %.2f' % PRF[2])
print('Logarithmic loss: %.2f' % log_loss(Y_test, Y_result,normalize=True))

3.0715861320495605
Accuracy: 0.87
Precision: 0.87
Recall: 0.87
F1: 0.87
Logarithmic loss: 4.36


In [53]:
# save the model to disk
filename = 'svm_2000.sav'
pickle.dump(clf, open(filename, 'wb'))

In [22]:
X = pd.read_csv('restricted_conc_3000.csv', index_col=[0]).sample(frac=1).reset_index(drop=True)
Y = X.pop('LABEL').values
X_train, X_test, Y_train, Y_test = train_test_split(X.values, Y, test_size=0.2)
clf = svm.SVC(kernel='rbf', gamma=0.1, C=100)
start = time.time()
clf.fit(X_train, Y_train)
end = time.time()
print(end - start)
Y_result = clf.predict(X_test)

print('Accuracy: %.4f' % accuracy_score(Y_test, Y_result))
PRF = precision_recall_fscore_support(Y_test, Y_result, average='macro')
print('Precision: %.4f' % PRF[0])
print('Recall: %.4f' % PRF[1])
print('F1: %.4f' % PRF[2])

1.4658513069152832
Accuracy: 0.6133
Precision: 0.6407
Recall: 0.6219
F1: 0.6030
